### ISSUE TITLE
Having Good Knowledge on Graphs !!

### ISSUE THREAD

**Issue by Harshith1263** [sayantant01/cobraa#15]
Graphs are One of the Most Important Data Structures and also Play a Very Crucial Role in Real Life Applications 
So I Want to Contribute on 
1. How Graphs are Implemented By Different Other Data Structures 
2. The Most Important Graph Algorithms BFS and DFS !! 

Can I Move Forward Sir ??

**Comment by sayantant01** [comment]
Yes Please go ahead
